### ISSUE TITLE
Interface with UR Dashboard Server

### ISSUE THREAD

**Issue by vickailiu** [ThomasTimm/ur_modern_driver#165]
as described here: https://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/dashboard-server-port-29999-15690/

The UR Dashboard Server interface could provide more informations such as robot state and control such as showing/dismiss the popup on dashboard.

Will the new driver integrate this part in, or it deviates the motivation of this driver?

**Comment by vickailiu** [comment]
I see some work done like #99 .

**Comment by gavanderhoorn** [comment]
What sort of functionality are you looking for that the dashboard could provide?

> The UR Dashboard Server interface could provide more informations such as robot state

I believe the dashboard server makes use of the same datastreams as are used by the driver to determine robot state (ie: booting, calibrating, etc). Could you be a bit more specific?

> and control such as showing/dismiss the popup on dashboard.

Showing popups may be interesting. See #5.

**Comment by vickailiu** [comment]
@gavanderhoorn I must admit that I didn't do my homework -- reading through issue lists well. For robot state, I mean "robotmode", "programState" and "safetymode". They provide valuable informations for controlling the robot via programs.

**Comment by gavanderhoorn** [comment]
All of those are part of the datastreams received by the driver, it may just be lacking publishers for them.

#143 may already cover some of them with the `RobotStatus` message.

**Comment by gavanderhoorn** [comment]
@vickailiu: I'm going to close this. Not because I don't believe there is any value in your question, but because this is not an actionable issue at the moment.

As I wrote in my earlier comment(s): the specific pieces of info you mention should already be part of the datastream(s) that the driver receives from the controller. If they are not already published, then adding a publisher for them (or some other way in which they could be retrieved) would seem to be the best course of action.

Afaict, the dashboard server seems to be another way of retrieving the same data, but adding support for that would require much more extensive changes than reusing the existing infrastructure.

**Comment by gavanderhoorn** [comment]
Do please feel free to keep commenting on this issue btw.

**Comment by vickailiu** [comment]
@gavanderhoorn agree.
