### ISSUE TITLE
Is it possible to add "Force"  function to ur_modern_driver?

### ISSUE THREAD

**Issue by yqy0805** [ThomasTimm/ur_modern_driver#67]
"Force" function provided by UR script is very useful to do some on-line control, such as "Spraying action", so is it possible to add "Force" function to ur_modern_driver?? @ThomasTimm

**Comment by ThomasTimm** [comment]
It is kind of possible, although the only way to do it is already implemented, which is why I close this issue (Also because it is not an issue).

ROS doesn't have any message type (afaik) that makes it possible to send force actions (what message type should the robot arm subscribe to?). 
Until such an action type is implemented (probably in control_msgs), I won't try to implement it on my own in the driver as partly the process of implementing it and inventing such and interface would be more time-consuming than what can be gained, as compared to just sending URScript commands, and partly because I would probably have to redesign it if/when a more standard action is defined in ROS.

You can use the /URScript topic to send force functions to the arm, the same way as when you program it without ROS.
